name: sktime
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip:
      - jupyterlab==4.1.4
      - matplotlib==3.8.3
      - numpy==1.26.4
      - pandas==2.1.4
      - sktime==0.27.0